GET {{HOST}}user/bank?pageSize=3&pageIndex=0
Authorization: Bearer {{auth_token}}
###
GET {{HOST}}user/bank
Authorization: Bearer {{auth_token}}
###
GET {{HOST}}user?pageSize=3&pageIndex=0
Authorization: Bearer {{auth_token}}
###
GET {{HOST}}user
Authorization: Bearer {{auth_token}}