const SALT_OR_ROUNDS = 10;
const ACTION_RECAPTCHA = ['login', 'register'];
const SCORE_RECAPTCHA = 0.8;
const REDIS_QUEUE_LIMIT_MAX = 5;
const REDIS_QUEUE_LIMIT_DURATION = 1000;
const REDIS_QUEUE_LIMIT_BOUNCEBACK = false;
export {
  SALT_OR_ROUNDS,
  ACTION_RECAPTCHA,
  SCORE_RECAPTCHA,
  REDIS_QUEUE_LIMIT_MAX,
  REDIS_QUEUE_LIMIT_DURATION,
  REDIS_QUEUE_LIMIT_BOUNCEBACK,
};
